### ISSUE TITLE
End game exception

### ISSUE THREAD

**Issue by Ravager1240** [andburn/hdt-plugin-endgame#25]
Had this issue after updating to 1.0.7
===============
End Game 1.0.7 threw an exception
------------------------------------------
Make sure you are using the latest version of the Plugin and HDT.

System.Windows.Markup.XamlParseException: Set connectionId threw an exception. ---> System.TypeLoadException: Could not load type 'Hearthstone_Deck_Tracker.Utility.Toasts.ToastControls.BaseToast' from assembly 'HearthstoneDeckTracker, Version=1.13.1.5042, Culture=neutral, PublicKeyToken=null'.
   at HDT.Plugins.Common.Controls.SimpleToast.System.Windows.Markup.IComponentConnector.Connect(Int32 connectionId, Object target)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetConnectionId(Object root, Int32 connectionId, Object instance)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at HDT.Plugins.Common.Controls.SimpleToast.InitializeComponent() in C:\projects\hdt-plugin-endgame\EndGame.Common\Controls\SimpleToast.xaml:line 1
   at HDT.Plugins.Common.Controls.SimpleToast..ctor(String title, String message, String icon, String url) in C:\projects\hdt-plugin-endgame\EndGame.Common\Controls\SimpleToast.xaml.cs:line 38
   at HDT.Plugins.Common.Utils.NotificationManager.ShowToast(String title, String message, String icon, String url) in C:\projects\hdt-plugin-endgame\EndGame.Common\Utils\NotificationManager.cs:line 21
   at HDT.Plugins.EndGame.EndGame.Notify(String title, String message, String icon, String url)
   at HDT.Plugins.EndGame.EndGame.<ImportMetaDecks>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HDT.Plugins.EndGame.EndGame.<OnLoad>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by andburn** [comment]
Thanks, I'll get this fixed.

**Comment by andburn** [comment]
Should be fixed now, try the latest version.
